#[cfg(test)]
mod ssl_tests {
    use crate::ssl::enums::certificate_error::CertificateError;
    use crate::ssl::enums::server_identifier::ServerIdentifier;
    use crate::ssl::structs::certificate_store::CertificateStore;
    use rcgen::{
        generate_simple_self_signed,
        CertifiedKey
    };
    use rustls::pki_types::pem::PemObject;
    use rustls::pki_types::PrivateKeyDer;
    use std::path::PathBuf;

    /// Writes a freshly generated self-signed certificate and its key into `dir`.
    fn write_self_signed(dir: &tempfile::TempDir) -> (PathBuf, PathBuf) {
        let CertifiedKey { cert, signing_key } =
            generate_simple_self_signed(vec!["localhost".to_string()]).unwrap();
        let cert_path = dir.path().join("cert.pem");
        let key_path = dir.path().join("key.pem");
        std::fs::write(&cert_path, cert.pem()).unwrap();
        std::fs::write(&key_path, signing_key.serialize_pem()).unwrap();
        (cert_path, key_path)
    }

    #[test]
    fn test_certificate_store_new() {
        let store = CertificateStore::new();
        assert!(store.all_servers().is_empty());
    }

    #[test]
    fn loads_a_real_certificate_and_key_from_disk() {
        let dir = tempfile::tempdir().unwrap();
        let (cert_path, key_path) = write_self_signed(&dir);
        let store = CertificateStore::new();
        let server_id = ServerIdentifier::HttpTracker("127.0.0.1:6969".to_string());

        store
            .load_certificate(
                server_id.clone(),
                cert_path.to_str().unwrap(),
                key_path.to_str().unwrap(),
            )
            .expect("a self-signed pair generated by rcgen must load");

        let bundle = store.get_certificate(&server_id).expect("bundle registered");
        assert_eq!(bundle.certs.len(), 1);
        // rcgen writes PKCS#8, the format every existing deployment has on disk.
        assert!(matches!(bundle.key, PrivateKeyDer::Pkcs8(_)));

        // Reloading from the registered paths must produce a working bundle again.
        store.reload_certificate(&server_id).expect("reload from stored paths");
        assert!(store.get_certificate(&server_id).is_some());
    }

    #[test]
    fn a_key_file_without_any_pem_section_reports_no_key_found() {
        let dir = tempfile::tempdir().unwrap();
        let (cert_path, _) = write_self_signed(&dir);
        let key_path = dir.path().join("empty.pem");
        std::fs::write(&key_path, "not a pem file at all\n").unwrap();

        let store = CertificateStore::new();
        let result = store.load_certificate(
            ServerIdentifier::ApiServer("127.0.0.1:8080".to_string()),
            cert_path.to_str().unwrap(),
            key_path.to_str().unwrap(),
        );
        assert!(matches!(result, Err(CertificateError::NoKeyFound)), "got {result:?}");
    }

    #[test]
    fn a_certificate_file_without_any_certificate_is_rejected() {
        let dir = tempfile::tempdir().unwrap();
        let (_, key_path) = write_self_signed(&dir);
        let cert_path = dir.path().join("empty-cert.pem");
        std::fs::write(&cert_path, "no certificates here\n").unwrap();

        let store = CertificateStore::new();
        let result = store.load_certificate(
            ServerIdentifier::ApiServer("127.0.0.1:8080".to_string()),
            cert_path.to_str().unwrap(),
            key_path.to_str().unwrap(),
        );
        assert!(matches!(result, Err(CertificateError::CertParseError(_))), "got {result:?}");
    }

    #[test]
    fn every_private_key_pem_section_maps_to_its_own_variant() {
        // The old loader reopened the key file once per format and only ever reached PKCS#1 and
        // SEC1 by falling through two earlier passes. One pass now covers all three, so the
        // section label alone has to select the right variant.
        let body = "MC4CAQAwBQYDK2VwBCIEIL9lYlNMIL6NBnLcnLXRJmYqHJqNMoLpBnGkKcJ0y7Ei\n";
        for (label, expect_pkcs8, expect_pkcs1, expect_sec1) in [
            ("PRIVATE KEY", true, false, false),
            ("RSA PRIVATE KEY", false, true, false),
            ("EC PRIVATE KEY", false, false, true),
        ] {
            let pem = format!("-----BEGIN {label}-----\n{body}-----END {label}-----\n");
            let key = PrivateKeyDer::from_pem_slice(pem.as_bytes())
                .unwrap_or_else(|e| panic!("{label} should parse: {e}"));
            assert_eq!(matches!(key, PrivateKeyDer::Pkcs8(_)), expect_pkcs8, "{label}");
            assert_eq!(matches!(key, PrivateKeyDer::Pkcs1(_)), expect_pkcs1, "{label}");
            assert_eq!(matches!(key, PrivateKeyDer::Sec1(_)), expect_sec1, "{label}");
        }
    }
}
